---

- name: Install AWS CLI dependencies
  ansible.builtin.apt:
    name:
      - unzip
    state: present
    cache_valid_time: 600
  become: true

- name: Download AWS CLI and signature file
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.{{ item }}"
    dest: "{{ aws_cli_download_dir }}/{{ aws_cli_filename }}.{{ item }}"
    mode: '400'
  with_items:
    - zip
    - zip.sig

- name: Copy key file
  ansible.builtin.copy:
    src: "{{ aws_cli_key_name }}"
    dest: "{{ aws_cli_key_path }}"
    mode: '400'

- name: Import GPG key
  ansible.builtin.shell:
    cmd: "gpg --import {{ aws_cli_key_path }}"
  args:
    executable: /bin/sh
  register: key_import
  changed_when: false
  failed_when: key_import.rc != 0

- name: Verify AWS CLI signature
  ansible.builtin.shell:
    cmd: "gpg --verify {{ aws_cli_download_dir }}/{{ aws_cli_filename }}.zip.sig {{ aws_cli_download_dir }}/{{ aws_cli_filename }}.zip"
  args:
    executable: /bin/sh
  register: verify
  changed_when: false
  failed_when: verify.rc != 0

- name: Unzip AWS CLI installer
  ansible.builtin.unarchive:
    src: "{{ aws_cli_download_dir }}/{{ aws_cli_filename }}.zip"
    dest: "{{ aws_cli_download_dir }}"
    copy: false
    creates: "{{ aws_cli_download_dir }}/aws"

- name: Install AWS CLI
  ansible.builtin.shell:
    cmd: "{{ aws_cli_download_dir }}/aws/install -i /usr/local/aws -b /usr/bin/aws"
  become: true
  args:
    executable: /bin/sh
    creates: /usr/bin/aws

- name: Cleanup downloaded files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ aws_cli_download_dir }}/{{ aws_cli_filename }}.zip"
    - "{{ aws_cli_download_dir }}/{{ aws_cli_filename }}.zip.sig"
    - "{{ aws_cli_key_path }}"
    - "{{ aws_cli_download_dir }}/aws"

- name: Get AWS CLI version
  ansible.builtin.shell:
    cmd: aws --version
  args:
    executable: /bin/sh
  register: version
  changed_when: false
  failed_when: version.rc != 0

- name: Print AWS CLI version
  ansible.builtin.debug:
    var: version.stdout
