galaxy_info:
  role_name: azure_cli_install
  author: frennky
  description: This role installs Azure CLI on local system.

  license: MIT

  min_ansible_version: 2.14.2

  platforms:
    - name: Debian
      versions:
        - bookworm

  galaxy_tags:
    - azure
    - cli
    - install

dependencies: []
