---
go_version: "1.22.1"
go_platform: linux
go_arch: amd64
go_tarball: "go{{ go_version }}.{{ go_platform }}-{{ go_arch }}.tar.gz"
go_download_url: "https://go.dev/dl/{{ go_tarball }}"
go_checksum: 'aab8e15785c997ae20f9c88422ee35d962c4562212bb0f879d052a35c8307c7f'
