galaxy_info:
  role_name: docker_install
  author: frennky
  description: This role installs Docker on local system.

  license: MIT

  min_ansible_version: 2.14.2

  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - docker
    - install

dependencies: []
