---

- name: Install Edge dependencies
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
    cache_valid_time: 600
  become: true

- name: Get Edge GPG key
  ansible.builtin.get_url:
    url: "{{ edge_pgp_url }}"
    dest: "{{ edge_pgp_path }}"
    mode: '644'
  become: true

- name: Add Edge repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ edge_arch }} signed-by={{ edge_pgp_path }}] {{ edge_repo_url }} {{ edge_repo }} main"
    filename: microsoft-edge
    state: present
  become: true

- name: Install Edge
  ansible.builtin.apt:
    name:
      - "{{ edge_package }}"
    cache_valid_time: 600
  become: true

- name: Get Edge version
  ansible.builtin.shell:
    cmd: microsoft-edge --version
  args:
    executable: /bin/sh
  register: version
  changed_when: false
  failed_when: version.rc != 0

- name: Print Edge version
  ansible.builtin.debug:
    var: version.stdout
