---
docker_key_url: "https://download.docker.com/linux/{{ ansible_facts.lsb.id | lower }}/gpg"
docker_key_path: "/etc/apt/keyrings/docker.asc"
docker_repo_url: "https://download.docker.com/linux/{{ ansible_facts.lsb.id | lower }}"
docker_arch: amd64
docker_repo: "{{ ansible_facts.lsb.codename }}"
