---
nvim_version: "v0.10.0"
nvim_platform: linux
nvim_arch: 64
nvim_tarball: "nvim-{{ nvim_platform }}{{ nvim_arch }}.tar.gz"
nvim_download_url: "https://github.com/neovim/neovim/releases/download/{{ nvim_version }}/{{ nvim_tarball }}"
nvim_checksum: 'be1f0988d0de71c375982b87b86cd28d2bab35ece8285abe3b0aac57604dfc5a'
nvchad_version: 'v2.5'
