---

- name: Remove conflicting dependencies
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent
  become: true

- name: Install Docker dependencies
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    cache_valid_time: 600
  become: true

- name: Get Docker GPG key
  ansible.builtin.get_url:
    url: "{{ docker_key_url }}"
    dest: "{{ docker_key_path }}"
    mode: '644'
  become: true

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ docker_arch }} signed-by={{ docker_key_path }}] {{ docker_repo_url }} {{ docker_repo }} stable"
    filename: docker
    state: present
  become: true

- name: Install Docker
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    cache_valid_time: 600
  become: true

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true

- name: Ensure user is in docker group
  ansible.builtin.user:
    name: "{{ lookup('env', 'USER') }}"
    groups: docker
    append: true
  become: true

- name: Get Docker version
  ansible.builtin.shell:
    cmd: docker --version
  args:
    executable: /bin/sh
  register: version
  changed_when: false
  failed_when: version.rc != 0

- name: Print Docker version
  ansible.builtin.debug:
    var: version.stdout
