---

- name: Facts
  hosts: localhost
  connection: local

  tasks:
    - name: Print all available facts
      ansible.builtin.debug:
        var: ansible_facts

    - name: Print distribution
      ansible.builtin.debug:
        var: ansible_facts.distribution

    - name: Print release
      ansible.builtin.debug:
        var: ansible_facts.distribution_release

    - name: Print version
      ansible.builtin.debug:
        var: ansible_facts.distribution_version

    - name: Print lsb id
      ansible.builtin.debug:
        var: ansible_facts.lsb.id

    - name: Print lsb release
      ansible.builtin.debug:
        var: ansible_facts.lsb.release

    - name: Print architecture
      ansible.builtin.debug:
        var: ansible_facts.architecture
