galaxy_info:
  role_name: nvim_install
  author: frennky
  description: This role installs NeoVim on local system.

  license: MIT

  min_ansible_version: 2.14.2

  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - nvim
    - install

dependencies: []
