---
terraform_key_url: https://apt.releases.hashicorp.com/gpg
terraform_key_path: /etc/apt/keyrings/hashicorp.asc
terraform_repo_url: https://apt.releases.hashicorp.com
terraform_repo: lunar
terraform_package: terraform
