---

- name: Remove existing installation
  ansible.builtin.file:
    path: /usr/local/nvim
    state: absent
  become: true

- name: Create destination dir
  ansible.builtin.file:
    path: /usr/local/nvim
    state: directory
    mode: '755'
  become: true

- name: Download and extract NeoVim tarball
  ansible.builtin.unarchive:
    src: "{{ nvim_download_url }}"
    remote_src: true
    dest: /usr/local/nvim
    extra_opts: ['--strip-components=1', '--show-stored-names']
  become: true

- name: Add NeoVim to system $PATH
  ansible.builtin.copy:
    dest: /etc/profile.d/nvim.sh
    content: |-
      export PATH=$PATH:/usr/local/nvim/bin
    mode: '644'
  become: true

- name: Get NeoVim version
  ansible.builtin.shell:
    cmd: /usr/local/nvim/bin/nvim --version
  args:
    executable: /bin/sh
  register: version
  changed_when: false
  failed_when: version.rc != 0

- name: Print NeoVim version
  ansible.builtin.debug:
    var: version.stdout

- name: Remove existing NvChad configuration
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - ~/.config/nvim
    - ~/.local/share/nvim

- name: Get NvChad configuration
  ansible.builtin.git:
    repo: 'https://github.com/NvChad/starter'
    dest: ~/.config/nvim
    version: "{{ nvchad_version }}"
